# Generated by Django 3.0.4 on 2020-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite o nome:')),
                ('idade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite a idade:')),
                ('altura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite a altura:')),
                ('peso', models.CharField(blank=True, max_length=20, null=True, verbose_name='peso')),

                ('febre', models.CharField(blank=True, max_length=20, null=True, verbose_name='febre')),
                ('cabeca', models.CharField(blank=True, max_length=20, null=True, verbose_name='cabeca')),

                ('nasal', models.CharField(blank=True, max_length=20, null=True, verbose_name='febre')),
                ('garganta', models.CharField(blank=True, max_length=20, null=True, verbose_name='cabeca')),
                ('tosse', models.CharField(blank=True, max_length=20, null=True, verbose_name='febre')),
                ('dificuldadeResp', models.CharField(blank=True, max_length=20, null=True, verbose_name='cabeca')),
                ('dorCorpo', models.CharField(blank=True, max_length=20, null=True, verbose_name='febre')),
                ('diarreia', models.CharField(blank=True, max_length=20, null=True, verbose_name='cabeca')),
                ('viajou', models.CharField(blank=True, max_length=20, null=True, verbose_name='febre')),
                ('contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='cabeca')),

                ('imc', models.CharField(blank=True, max_length=20, null=True, verbose_name='imc')),
                ('data', models.CharField(blank=True, max_length=20, null=True, verbose_name='XXXX')),
                ('hora', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hora da triagem')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'objeto',
                'verbose_name_plural': 'objetos',
            },
        ),
    ]
